kafka.producer:
  servers: ''
  retries: '5'
  batch.size: '32000'
  publish.path: /kafka/publish
  linger.ms: '10'
  buffer.memory: ''
  port: null
  client.id: test
  acks: '1'
  retry.backoff.ms: '1000'
  reconnect.backoff.ms: '1000'
  key.serializer: org.apache.kafka.common.serialization.StringSerializer
  value.serializer: org.apache.kafka.common.serialization.StringSerializer
kafka.consumers:
  servers: ''
  enable.auto.commit: 'false'
  auto.commit.interval: ''
  auto.offset.reset: ''
  group.id: ''
  topic: ''
  concurrency: ''
  callback.url: ''
  failure.topic: ''
  failure.retries: 3
  dead.topic: ''
  dead.callback.url: ''
  max.partition.fetch.bytes: '1000000'
  key.deserializer: ''
  value.deserializer: ''
