elasticsearch.host: 192.168.0.1
elasticsearch.port: 5600
path.data: /var/lib/elasticsearch
path.logs: /path/to/logs
path.conf: /path/to/conf
path.work: /path/to/work
path.plugins: /path/to/plugins
gateway.recover_after_nodes: 3
gateway.recover_after_time: 10m
action.destructive_requires_name: true
cluster.name: od-fts1
node.name: ''
node.master: true
node.data: true
index.number_of_shards: 2
index.number_of_replicas: 1
action.disable_close_all_indices: true
action.disable_delete_all_indices: true
action.disable_shutdown: true
bootstrap.mlockall: true
